import { baseCardId, normalizeCardId } from "./cards";
import { foldHan } from "./hanVariants";

/**
 * One game card's skill data, as the card master ships it. The six skill fields
 * keep the game's own text verbatim — including the `//` that separates the
 * pre-evolution list from the post-evolution one — so this is a faithful source
 * to copy from when writing a patch.
 *
 * The data is generated by scripts/build-card-reference.mjs and lives in its own
 * module, loaded on demand: the effect text alone is over a megabyte, far too
 * much to sit in the main bundle next to the always-needed card name catalog.
 */
export interface CardReferenceEntry {
  id: number;
  /** The six parallel CardMaster skill fields, verbatim. */
  skill: string;
  timing: string;
  condition: string;
  target: string;
  option: string;
  preprocess: string;
  /** Localised effect text, with the game's markup still in it. */
  description: string;
  /** Effect text shown only after evolving; some cards put everything here. */
  evoDescription: string;
  /** `skill_effect_condition`, a seventh field the skill editor does not model. */
  effectCondition: string;
  /** Presentation columns for the pre-evolution skills. */
  effectPath: string;
  sePath: string;
  moveType: string;
  engineType: string;
  effectTime: string;
  targetType: string;
  /** Presentation columns for the post-evolution skills; the game has no evo target type. */
  evoEffectPath: string;
  evoSePath: string;
  evoMoveType: string;
  evoEngineType: string;
  evoEffectTime: string;
  /** `description` with markup removed, for display. */
  text: string;
  /** `evoDescription` with markup removed, for display. */
  evoText: string;
  /** Lowercased effect text and skill fields, concatenated for substring search. */
  haystack: string;
}

/**
 * Blob column order. Checked against `cardReferenceColumns` from the generated
 * module at load time, so a generator change that reorders columns fails loudly
 * instead of shifting every field by one.
 */
const COLUMNS = [
  "idDelta",
  "skill", "timing", "condition", "target", "option", "preprocess",
  "description", "evoDescription", "effectCondition",
  "effectPath", "sePath", "moveType", "engineType", "effectTime", "targetType",
  "evoEffectPath", "evoSePath", "evoMoveType", "evoEngineType", "evoEffectTime",
] as const;

/** Shortest line the generator can emit; the rest of the columns are trimmed when empty. */
const REQUIRED_COLUMNS = 7;

/**
 * Presentation markup in the effect text: `[u]`/`[/u]` for underline, a six digit
 * hex colour opened by `[ffcd45]` and closed by `[-]`, and `<<...>>` around
 * keyword names. `${...}` placeholders are left alone — `${me.hand_self.count}`
 * says more about the card than a blank would, and it is worth searching for.
 */
const MARKUP = /\[(?:\/?[a-zA-Z]{1,12}|-|[0-9a-fA-F]{6})\]|<<|>>/g;

export function stripCardTextMarkup(text: string) {
  return text.replace(MARKUP, "").trim();
}

function decodeReferenceBlob(blob: string, columns: readonly string[]): CardReferenceEntry[] {
  if (columns.length !== COLUMNS.length || columns.some((name, index) => name !== COLUMNS[index])) {
    throw new Error(`列顺序与解码器不一致：${columns.join(",")}`);
  }
  const entries: CardReferenceEntry[] = [];
  let id = 0;
  // Records are literal newlines inside the generated template literal, so a CRLF
  // checkout would leave a stray \r in the last column of every row — and that
  // column ends up inside a copied DSL string. Tolerated here rather than trusted
  // to .gitattributes alone.
  const lines = blob.split(/\r?\n/);
  for (let index = 0; index < lines.length; index++) {
    const line = lines[index];
    if (!line) continue;
    const parts = line.split("~");
    // A short line would desync every following delta, so refuse the whole blob.
    if (parts.length < REQUIRED_COLUMNS || parts.length > COLUMNS.length) {
      throw new Error(`第 ${index + 1} 行有 ${parts.length} 个字段，期望 ${REQUIRED_COLUMNS} 到 ${COLUMNS.length} 个。`);
    }
    const delta = Number(parts[0]);
    if (!Number.isInteger(delta)) throw new Error(`第 ${index + 1} 行的 ID 增量不是整数。`);
    id += delta;
    const at = (column: (typeof COLUMNS)[number]) => parts[COLUMNS.indexOf(column)] ?? "";
    const description = at("description");
    const evoDescription = at("evoDescription");
    const text = stripCardTextMarkup(description);
    const evoText = stripCardTextMarkup(evoDescription);
    const entry: CardReferenceEntry = {
      id,
      skill: at("skill"),
      timing: at("timing"),
      condition: at("condition"),
      target: at("target"),
      option: at("option"),
      preprocess: at("preprocess"),
      description,
      evoDescription,
      effectCondition: at("effectCondition"),
      effectPath: at("effectPath"),
      sePath: at("sePath"),
      moveType: at("moveType"),
      engineType: at("engineType"),
      effectTime: at("effectTime"),
      targetType: at("targetType"),
      evoEffectPath: at("evoEffectPath"),
      evoSePath: at("evoSePath"),
      evoMoveType: at("evoMoveType"),
      evoEngineType: at("evoEngineType"),
      evoEffectTime: at("evoEffectTime"),
      text,
      evoText,
      haystack: "",
    };
    // Only the cleaned text is indexed: the raw copy differs from it by markup
    // alone, so searching both would double the memory for no extra hit. Folded to
    // simplified Han here rather than per search, so a traditional export costs
    // nothing extra to search in simplified.
    entry.haystack = foldHan([text, evoText, entry.skill, entry.timing, entry.condition, entry.target, entry.option, entry.preprocess, entry.effectCondition]
      .filter(Boolean)
      .join(" ")
      .toLowerCase());
    entries.push(entry);
  }
  return entries;
}

export interface CardReference {
  readonly entries: readonly CardReferenceEntry[];
  /** False when the source export predates `evo_skill_description`; evolution only text is then missing. */
  readonly hasEvoText: boolean;
  /** Set when the bundled data could not be decoded, so the panel can say why it is empty. */
  readonly error?: string;
  get(cardId: number | string | null | undefined): CardReferenceEntry | undefined;
}

function buildReference(entries: CardReferenceEntry[], hasEvoText: boolean, error?: string): CardReference {
  const byId = new Map(entries.map((entry) => [entry.id, entry]));
  return {
    entries,
    hasEvoText,
    error,
    get(cardId) {
      const id = normalizeCardId(cardId);
      if (id == null) return undefined;
      return byId.get(id) ?? byId.get(baseCardId(id));
    },
  };
}

/**
 * Decodes a blob into a searchable reference. Exported so the generated chunk is
 * not the only way in: tests and any future non-bundled source use this.
 */
export function createCardReference(blob: string, columns: readonly string[] = COLUMNS, hasEvoText = true): CardReference {
  return buildReference(decodeReferenceBlob(blob, columns), hasEvoText);
}

let pending: Promise<CardReference> | null = null;

/**
 * Loads the bundled skill reference, decoding it once. The dynamic import keeps
 * the generated module in its own chunk, so opening the reference panel is what
 * downloads it rather than every visit to the editor.
 *
 * A corrupt or missing chunk resolves to an empty reference carrying the reason
 * instead of rejecting: the panel then shows the message and the rest of the
 * editor is unaffected.
 */
export function loadCardReference(): Promise<CardReference> {
  pending ??= import("./cardReference.generated")
    .then(({ cardReferenceBlob, cardReferenceColumns, cardReferenceCount, cardReferenceHasEvoText }) => {
      const entries = decodeReferenceBlob(cardReferenceBlob, cardReferenceColumns);
      if (entries.length !== cardReferenceCount) throw new Error(`解码得到 ${entries.length} 条记录，期望 ${cardReferenceCount} 条。`);
      return buildReference(entries, cardReferenceHasEvoText);
    })
    .catch((reason: unknown) => {
      console.error("内置卡牌技能参考数据加载失败。请重新运行 npm run build:reference。", reason);
      const detail = reason instanceof Error ? reason.message : String(reason);
      return buildReference([], false, `技能参考数据加载失败：${detail}`);
    });
  return pending;
}

export interface CardReferenceMatch {
  entry: CardReferenceEntry;
  /** Card name from the always bundled catalog, when it knows this ID. */
  name?: string;
  /** Which part of the row the query hit, for the badge on the result row. */
  hit: "id" | "name" | "text" | "skill";
}

export interface CardReferenceSearch {
  matches: CardReferenceMatch[];
  /** Matches before `limit` was applied, so the panel can say how many are hidden. */
  total: number;
}

/**
 * Searches the reference by ID, card name, effect text or raw skill field.
 *
 * Whitespace separated words all have to match somewhere in the row, so
 * "疾驰 突进" narrows instead of widening. A purely numeric query of four digits
 * or more is treated as an ID search, which is the only way to look up a card
 * whose name the bundled catalog does not know.
 *
 * Comparison happens in folded Han (see `foldHan`), so simplified and traditional
 * spellings find each other in either direction — the bundled data is traditional
 * and the UI is simplified, so this is the normal case rather than an edge one.
 */
export function searchCardReference(
  reference: CardReference,
  query: string,
  name: (cardId: number) => string | undefined,
  limit = 60,
): CardReferenceSearch {
  const trimmed = foldHan(query.trim().toLowerCase());
  if (!trimmed) return { matches: [], total: 0 };
  const words = trimmed.split(/\s+/).filter(Boolean);
  const numeric = /^\d{4,}$/.test(trimmed);

  const found: CardReferenceMatch[] = [];
  for (const entry of reference.entries) {
    const cardName = name(entry.id);
    // The name is folded per row rather than cached: it is a handful of characters
    // against a haystack scan that costs far more in the same loop.
    const lowerName = cardName ? foldHan(cardName.toLowerCase()) : "";
    const id = String(entry.id);
    let hit: CardReferenceMatch["hit"] | null = null;
    if (numeric && id.includes(trimmed)) {
      hit = "id";
    } else if (words.every((word) => lowerName.includes(word))) {
      hit = "name";
    } else if (words.every((word) => lowerName.includes(word) || entry.haystack.includes(word))) {
      // The cleaned effect text comes first in the haystack, so prefer calling
      // this a text hit and fall back to skill only when the text cannot explain it.
      const inText = words.every((word) => lowerName.includes(word) || foldHan(entry.text.toLowerCase()).includes(word) || foldHan(entry.evoText.toLowerCase()).includes(word));
      hit = inText ? "text" : "skill";
    }
    if (hit) found.push({ entry, name: cardName, hit });
  }

  // Ranked before slicing, so a name hit near the end of the table still beats a
  // text hit near the start: name first, then text, then raw skill fields, with
  // ID order inside each rank keeping cards from one expansion together.
  const rank = { id: 0, name: 1, text: 2, skill: 3 };
  found.sort((left, right) => rank[left.hit] - rank[right.hit] || left.entry.id - right.entry.id);
  return { matches: found.slice(0, limit), total: found.length };
}
